# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xWyHdIUeoaAlY308mPtviMrBPq_COKQz
"""

# Instalar pt_BR

!/usr/share/locales/install-language-pack pt_BR

!dpkg-reconfigure locales

# Reiniciar o processo Python

os.kill(os.getpid(), 9)

import pandas as pd
from datetime import datetime

# Criando um arquivo CSV com os dados
csv_filename = "cadastros.csv"
dados = """nome,dataNasc,dataCadastrado,horaCadastro
Jared Jhonson,05/04/1977,2025/02/17,21:40
Erik Klepton,26/04/1995,2025/02/17,23:31
Stive Rogers,15/08/1988,2025/02/17,20:32
Arlindo Da Silva,07/05/2000,2025/02/17,20:39
Jobson,05/05/1999,2025/02/17,15:40
"""

# Salvando os dados no arquivo CSV
with open(csv_filename, "w") as file:
    file.write(dados)

# Lendo o arquivo CSV
df = pd.read_csv(csv_filename)

# Função para converter datas para o formato brasileiro (DD/MM/AAAA)
def formatar_data(data, formato_entrada="%m/%d/%Y", formato_saida="%d/%m/%Y"):
    return datetime.strptime(data, formato_entrada).strftime(formato_saida)

# Solicitando ao usuário o número do registro desejado
registro_n = int(input("Digite o número do registro que deseja visualizar (1 a 5): "))

# Verificando se o número é válido
if 1 <= registro_n <= len(df):
    registro = df.iloc[registro_n - 1]

    # Formatando as datas
    data_nascimento_br = formatar_data(registro["dataNasc"])
    data_cadastro_br = formatar_data(registro["dataCadastrado"], "%Y/%m/%d")

    # Exibindo o registro formatado
    print(f"Registro {registro_n}: Nome: {registro['nome']}; Data de nascimento: {data_nascimento_br}; ")
    print(f"Data de cadastro: {data_cadastro_br} às {registro['horaCadastro']} horas")
else:
    print("Número de registro inválido! Escolha um número entre 1 e 5.")